### ISSUE TITLE
scroll 

### ISSUE THREAD

**Issue by CDragon03** [tg123/RaidLedger#1]
The page will move in progress, but... I couldn't scroll and the item I ate in the beginning was not corrected and I can't see it.

**Comment by tg123** [comment]
not quite understand

could you please the steps how to repro the bug?

**Comment by CDragon03** [comment]
![i14181695896](https://user-images.githubusercontent.com/57742723/68834671-aa2e3600-06f9-11ea-88b9-a51536e303a2.jpg)
![i14113935362](https://user-images.githubusercontent.com/57742723/68834685-ae5a5380-06f9-11ea-8a79-cbf15cbc21f5.jpg)

**Comment by CDragon03** [comment]
Are you going to update me?

**Comment by tg123** [comment]
for sure
but I just tested in 1.13.2 the scroll does work

could you please provide any more information?

**Comment by CDragon03** [comment]
![i14181695896](https://user-images.githubusercontent.com/57742723/68840490-3181a680-0706-11ea-9f05-21791cfe944a.jpg)


The scroll part on the right is not good.

**Comment by tg123** [comment]
please provide me game version
addon version
and set
/console scriptErrors 1

disable all other addon and try again

copy/paste any lua error if your saw any

**Comment by CDragon03** [comment]
Thank you very much.I'll try.

**Comment by CDragon03** [comment]
When I was looking for various methods, there was a clash with the add-on called [ ClassicRaidTracker ]

**Comment by tg123** [comment]
Ah thank you I think I know what is the problem.
I will give out the fix by the end of the day

BTW, the koKR  is translated by a friend who does not play Wow at all,
maybe you could help about the localization at
https://www.curseforge.com/wow/addons/raidledger/localization
for better and more accurate words.

**Comment by tg123** [comment]
should be fixed by f00eb4fc09bddbd20c6965db06ddb3026ab4cecb

please try latest test version
https://www.curseforge.com/wow/addons/raidledger/files/2827400

**Comment by CDragon03** [comment]
Thank you very much.
I'll talk after I have tested.

**Comment by tg123** [comment]
fixed and tested
https://www.curseforge.com/wow/addons/raidledger/files/2827474

**Comment by CDragon03** [comment]
Thank you for the quick fix.
