### ISSUE TITLE
希望增加带有标记的报告

### ISSUE THREAD

**Issue by DancingDolphins** [tg123/RaidLedger#10]
其实很简单。针对一些可以使用图形的报告可以适当改为图形替换。使报告具有可读性比如：
![image](https://user-images.githubusercontent.com/30310389/147796495-dd996066-732e-4534-8571-0b6b1d4cf426.png)
可以将收入定为绿色三角
可以将金币定义为大饼
可以将数字从（1）变更为x1或者数量为1的不要写入（1）
![image](https://user-images.githubusercontent.com/30310389/147796620-e7d4406f-6173-4e1d-8094-72a535a877d6.png)
虽然说有点不切实际。但是还是希望可以针对BOSS进行分段。
比如：
![image](https://user-images.githubusercontent.com/30310389/147796977-bbe9948a-b680-4ebe-997d-2393a380ce83.png)

如果需要在NGA发帖我去NGA也发一份

**Comment by tg123** [comment]
不需要到 nga 发帖
不过我不太确定我理解你的意思 
是指 给 收入支出加一个符号 方便阅读对吗 

我觉得是个好主意

**Comment by DancingDolphins** [comment]
是的。可以用{rt1}-{rt8}来使用8个标记。

**Comment by DancingDolphins** [comment]
![image](https://user-images.githubusercontent.com/30310389/147797460-ce699a24-f661-497b-b4a5-8b98625eef5e.png)
如果要让所有语言客户端适配。请使用{rt1-8}
中文客户端无法使用{Star}等基于英文的标记

**Comment by tg123** [comment]
https://www.wowace.com/projects/raidledger/files/3592186
