### ISSUE TITLE
WoW Classic Era (1.15.4) - Addon no longer properly working

### ISSUE THREAD

**Issue by maximus210793** [tg123/RaidLedger#18]
Hi,
Could you update it to the latest Classic Era Game  Version of 1.15.4, since the addon is no longer working properly?
Would be awesome, thanks a lot in advance!

**Comment by tg123** [comment]
will take a look this weekend

**Comment by maximus210793** [comment]
thanks mate, when will the fix be available?

**Comment by tg123** [comment]
published last week 
let me know if it works for you 

https://www.curseforge.com/wow/addons/raidledger/files/5770067

**Comment by maximus210793** [comment]
works again thanks <3
