### ISSUE TITLE
Feature Request: Trade tracking and updates

### ISSUE THREAD

**Issue by ColdLogical** [tg123/RaidLedger#4]
Great addon, thank you a lot for making it.

I was wonder if its possible to add a feature. I would like the ledger to update if I trade the item to someone and they trade me gold at the same time. Currently, our master looter (me) just loots all the items from the boss, and then we auction them off later at the end of the raid. I then have to manually update all the gold amounts and the names for each item. Each item is already assigned to me since I sent it to myself, so basically everything has to be redone.

Someone made a fan fix to it, but obviously didn't provide you with the code or mention it, probably because they don't know how to communicate it. Here is a link with a download at top [http://www.inven.co.kr/board/wow/5531/1322](url)

**Comment by tg123** [comment]
trading into ledger is the feature which was added long time ago
there is a checkbox under the trade window for you to choose if you want current trade to be recorded
