### ISSUE TITLE
未结清功能使用BUG

### ISSUE THREAD

**Issue by T3rdW** [tg123/RaidLedger#8]
![image](https://user-images.githubusercontent.com/14792476/142822545-b0ae6ee8-8855-4e64-aa8b-2ea94d495a5e.png)
使用的最新版,点击未结清功能,只能选择第一个,后面几个都无法进行标记.望核实.

**Comment by tg123** [comment]
fixed in 4d62b3dee82ce00133c0c7e0b639b0e395fdf98d
