### ISSUE TITLE
Auto recording blacklist scrollframe is beyond the background frame

### ISSUE THREAD

**Issue by Verf** [tg123/RaidLedger#9]
![1](https://user-images.githubusercontent.com/22053969/142864057-7c5e8994-7eea-4ed2-8e45-28f43fb6745a.png)

上次更新([524bf6](https://github.com/tg123/RaidLedger/commit/524bf6789c616ae935c837acbd4cc26645f67e85))给拾取黑名单的编辑框增加了背景，但是没有调整几个frame之间的大小。导致scrollframe超过背景长度了。

**Comment by tg123** [comment]
fixed by 24bc80defc4ac4a37f57e14279ee367e23d31588
